/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50714
Source Host           : 127.0.0.1:3306
Source Database       : pos

Target Server Type    : MYSQL
Target Server Version : 50714
File Encoding         : 65001

Date: 2018-04-07 10:26:59
*/

SET FOREIGN_KEY_CHECKS=0;
use tropical;
-- ----------------------------
-- Table structure for pais
-- ----------------------------
DROP TABLE IF EXISTS `pais`;
CREATE TABLE `pais` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) DEFAULT NULL,
  `iso2` varchar(2) DEFAULT NULL,
  `iso3` varchar(3) DEFAULT NULL,
  `codigoTelefono` int(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=247 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of pais
-- ----------------------------
INSERT INTO `pais` VALUES ('1', 'AFGANISTÁN', 'AF', 'AFG', '93');
INSERT INTO `pais` VALUES ('2', 'ALBANIA', 'AL', 'ALB', '355');
INSERT INTO `pais` VALUES ('3', 'ALEMANIA', 'DE', 'DEU', '49');
INSERT INTO `pais` VALUES ('4', 'ALGERIA', 'DZ', 'DZA', '213');
INSERT INTO `pais` VALUES ('5', 'ANDORRA', 'AD', 'AND', '376');
INSERT INTO `pais` VALUES ('6', 'ANGOLA', 'AO', 'AGO', '244');
INSERT INTO `pais` VALUES ('7', 'ANGUILA', 'AI', 'AIA', '1264');
INSERT INTO `pais` VALUES ('8', 'ANTÁRTIDA', 'AQ', 'ATA', '672');
INSERT INTO `pais` VALUES ('9', 'ANTIGUA Y BARBUDA', 'AG', 'ATG', '1268');
INSERT INTO `pais` VALUES ('10', 'ANTILLAS NEERLANDESAS', 'AN', 'ANT', '599');
INSERT INTO `pais` VALUES ('11', 'ARABIA SAUDITA', 'SA', 'SAU', '966');
INSERT INTO `pais` VALUES ('12', 'ARGENTINA', 'AR', 'ARG', '54');
INSERT INTO `pais` VALUES ('13', 'ARMENIA', 'AM', 'ARM', '374');
INSERT INTO `pais` VALUES ('14', 'ARUBA', 'AW', 'ABW', '297');
INSERT INTO `pais` VALUES ('15', 'AUSTRALIA', 'AU', 'AUS', '61');
INSERT INTO `pais` VALUES ('16', 'AUSTRIA', 'AT', 'AUT', '43');
INSERT INTO `pais` VALUES ('17', 'AZERBAYÁN', 'AZ', 'AZE', '994');
INSERT INTO `pais` VALUES ('18', 'BÉLGICA', 'BE', 'BEL', '32');
INSERT INTO `pais` VALUES ('19', 'BAHAMAS', 'BS', 'BHS', '1242');
INSERT INTO `pais` VALUES ('20', 'BAHREIN', 'BH', 'BHR', '973');
INSERT INTO `pais` VALUES ('21', 'BANGLADESH', 'BD', 'BGD', '880');
INSERT INTO `pais` VALUES ('22', 'BARBADOS', 'BB', 'BRB', '1246');
INSERT INTO `pais` VALUES ('23', 'BELICE', 'BZ', 'BLZ', '501');
INSERT INTO `pais` VALUES ('24', 'BENÍN', 'BJ', 'BEN', '229');
INSERT INTO `pais` VALUES ('25', 'BHUTÁN', 'BT', 'BTN', '975');
INSERT INTO `pais` VALUES ('26', 'BIELORRUSIA', 'BY', 'BLR', '375');
INSERT INTO `pais` VALUES ('27', 'BIRMANIA', 'MM', 'MMR', '95');
INSERT INTO `pais` VALUES ('28', 'BOLIVIA', 'BO', 'BOL', '591');
INSERT INTO `pais` VALUES ('29', 'BOSNIA Y HERZEGOVINA', 'BA', 'BIH', '387');
INSERT INTO `pais` VALUES ('30', 'BOTSUANA', 'BW', 'BWA', '267');
INSERT INTO `pais` VALUES ('31', 'BRASIL', 'BR', 'BRA', '55');
INSERT INTO `pais` VALUES ('32', 'BRUNÉI', 'BN', 'BRN', '673');
INSERT INTO `pais` VALUES ('33', 'BULGARIA', 'BG', 'BGR', '359');
INSERT INTO `pais` VALUES ('34', 'BURKINA FASO', 'BF', 'BFA', '226');
INSERT INTO `pais` VALUES ('35', 'BURUNDI', 'BI', 'BDI', '257');
INSERT INTO `pais` VALUES ('36', 'CABO VERDE', 'CV', 'CPV', '238');
INSERT INTO `pais` VALUES ('37', 'CAMBOYA', 'KH', 'KHM', '855');
INSERT INTO `pais` VALUES ('38', 'CAMERÚN', 'CM', 'CMR', '237');
INSERT INTO `pais` VALUES ('39', 'CANADÁ', 'CA', 'CAN', '1');
INSERT INTO `pais` VALUES ('40', 'CHAD', 'TD', 'TCD', '235');
INSERT INTO `pais` VALUES ('41', 'CHILE', 'CL', 'CHL', '56');
INSERT INTO `pais` VALUES ('42', 'CHINA', 'CN', 'CHN', '86');
INSERT INTO `pais` VALUES ('43', 'CHIPRE', 'CY', 'CYP', '357');
INSERT INTO `pais` VALUES ('44', 'CIUDAD DEL VATICANO', 'VA', 'VAT', '39');
INSERT INTO `pais` VALUES ('45', 'COLOMBIA', 'CO', 'COL', '57');
INSERT INTO `pais` VALUES ('46', 'COMORAS', 'KM', 'COM', '269');
INSERT INTO `pais` VALUES ('47', 'CONGO', 'CG', 'COG', '242');
INSERT INTO `pais` VALUES ('48', 'CONGO', 'CD', 'COD', '243');
INSERT INTO `pais` VALUES ('49', 'COREA DEL NORTE', 'KP', 'PRK', '850');
INSERT INTO `pais` VALUES ('50', 'COREA DEL SUR', 'KR', 'KOR', '82');
INSERT INTO `pais` VALUES ('51', 'COSTA DE MARFIL', 'CI', 'CIV', '225');
INSERT INTO `pais` VALUES ('52', 'COSTA RICA', 'CR', 'CRI', '506');
INSERT INTO `pais` VALUES ('53', 'CROACIA', 'HR', 'HRV', '385');
INSERT INTO `pais` VALUES ('54', 'CUBA', 'CU', 'CUB', '53');
INSERT INTO `pais` VALUES ('55', 'DINAMARCA', 'DK', 'DNK', '45');
INSERT INTO `pais` VALUES ('56', 'DOMINICA', 'DM', 'DMA', '1767');
INSERT INTO `pais` VALUES ('57', 'ECUADOR', 'EC', 'ECU', '593');
INSERT INTO `pais` VALUES ('58', 'EGIPTO', 'EG', 'EGY', '20');
INSERT INTO `pais` VALUES ('59', 'EL SALVADOR', 'SV', 'SLV', '503');
INSERT INTO `pais` VALUES ('60', 'EMIRATOS ÁRABES UNIDOS', 'AE', 'ARE', '971');
INSERT INTO `pais` VALUES ('61', 'ERITREA', 'ER', 'ERI', '291');
INSERT INTO `pais` VALUES ('62', 'ESLOVAQUIA', 'SK', 'SVK', '421');
INSERT INTO `pais` VALUES ('63', 'ESLOVENIA', 'SI', 'SVN', '386');
INSERT INTO `pais` VALUES ('64', 'ESPAÑA', 'ES', 'ESP', '34');
INSERT INTO `pais` VALUES ('65', 'ESTADOS UNIDOS DE AMÉRICA', 'US', 'USA', '1');
INSERT INTO `pais` VALUES ('66', 'ESTONIA', 'EE', 'EST', '372');
INSERT INTO `pais` VALUES ('67', 'ETIOPÍA', 'ET', 'ETH', '251');
INSERT INTO `pais` VALUES ('68', 'FILIPINAS', 'PH', 'PHL', '63');
INSERT INTO `pais` VALUES ('69', 'FINLANDIA', 'FI', 'FIN', '358');
INSERT INTO `pais` VALUES ('70', 'FIYI', 'FJ', 'FJI', '679');
INSERT INTO `pais` VALUES ('71', 'FRANCIA', 'FR', 'FRA', '33');
INSERT INTO `pais` VALUES ('72', 'GABÓN', 'GA', 'GAB', '241');
INSERT INTO `pais` VALUES ('73', 'GAMBIA', 'GM', 'GMB', '220');
INSERT INTO `pais` VALUES ('74', 'GEORGIA', 'GE', 'GEO', '995');
INSERT INTO `pais` VALUES ('75', 'GHANA', 'GH', 'GHA', '233');
INSERT INTO `pais` VALUES ('76', 'GIBRALTAR', 'GI', 'GIB', '350');
INSERT INTO `pais` VALUES ('77', 'GRANADA', 'GD', 'GRD', '1473');
INSERT INTO `pais` VALUES ('78', 'GRECIA', 'GR', 'GRC', '30');
INSERT INTO `pais` VALUES ('79', 'GROENLANDIA', 'GL', 'GRL', '299');
INSERT INTO `pais` VALUES ('80', 'GUADALUPE', 'GP', 'GLP', '0');
INSERT INTO `pais` VALUES ('81', 'GUAM', 'GU', 'GUM', '1671');
INSERT INTO `pais` VALUES ('82', 'GUATEMALA', 'GT', 'GTM', '502');
INSERT INTO `pais` VALUES ('83', 'GUAYANA FRANCESA', 'GF', 'GUF', '0');
INSERT INTO `pais` VALUES ('84', 'GUERNSEY', 'GG', 'GGY', '0');
INSERT INTO `pais` VALUES ('85', 'GUINEA', 'GN', 'GIN', '224');
INSERT INTO `pais` VALUES ('86', 'GUINEA ECUATORIAL', 'GQ', 'GNQ', '240');
INSERT INTO `pais` VALUES ('87', 'GUINEA-BISSAU', 'GW', 'GNB', '245');
INSERT INTO `pais` VALUES ('88', 'GUYANA', 'GY', 'GUY', '592');
INSERT INTO `pais` VALUES ('89', 'HAITÍ', 'HT', 'HTI', '509');
INSERT INTO `pais` VALUES ('90', 'HONDURAS', 'HN', 'HND', '504');
INSERT INTO `pais` VALUES ('91', 'HONG KONG', 'HK', 'HKG', '852');
INSERT INTO `pais` VALUES ('92', 'HUNGRÍA', 'HU', 'HUN', '36');
INSERT INTO `pais` VALUES ('93', 'INDIA', 'IN', 'IND', '91');
INSERT INTO `pais` VALUES ('94', 'INDONESIA', 'ID', 'IDN', '62');
INSERT INTO `pais` VALUES ('95', 'IRÁN', 'IR', 'IRN', '98');
INSERT INTO `pais` VALUES ('96', 'IRAK', 'IQ', 'IRQ', '964');
INSERT INTO `pais` VALUES ('97', 'IRLANDA', 'IE', 'IRL', '353');
INSERT INTO `pais` VALUES ('98', 'ISLA BOUVET', 'BV', 'BVT', '0');
INSERT INTO `pais` VALUES ('99', 'ISLA DE MAN', 'IM', 'IMN', '44');
INSERT INTO `pais` VALUES ('100', 'ISLA DE NAVIDAD', 'CX', 'CXR', '61');
INSERT INTO `pais` VALUES ('101', 'ISLA NORFOLK', 'NF', 'NFK', '0');
INSERT INTO `pais` VALUES ('102', 'ISLANDIA', 'IS', 'ISL', '354');
INSERT INTO `pais` VALUES ('103', 'ISLAS BERMUDAS', 'BM', 'BMU', '1441');
INSERT INTO `pais` VALUES ('104', 'ISLAS CAIMÁN', 'KY', 'CYM', '1345');
INSERT INTO `pais` VALUES ('105', 'ISLAS COCOS (KEELING)', 'CC', 'CCK', '61');
INSERT INTO `pais` VALUES ('106', 'ISLAS COOK', 'CK', 'COK', '682');
INSERT INTO `pais` VALUES ('107', 'ISLAS DE ÅLAND', 'AX', 'ALA', '0');
INSERT INTO `pais` VALUES ('108', 'ISLAS FEROE', 'FO', 'FRO', '298');
INSERT INTO `pais` VALUES ('109', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'GS', 'SGS', '0');
INSERT INTO `pais` VALUES ('110', 'ISLAS HEARD Y MCDONALD', 'HM', 'HMD', '0');
INSERT INTO `pais` VALUES ('111', 'ISLAS MALDIVAS', 'MV', 'MDV', '960');
INSERT INTO `pais` VALUES ('112', 'ISLAS MALVINAS', 'FK', 'FLK', '500');
INSERT INTO `pais` VALUES ('113', 'ISLAS MARIANAS DEL NORTE', 'MP', 'MNP', '1670');
INSERT INTO `pais` VALUES ('114', 'ISLAS MARSHALL', 'MH', 'MHL', '692');
INSERT INTO `pais` VALUES ('115', 'ISLAS PITCAIRN', 'PN', 'PCN', '870');
INSERT INTO `pais` VALUES ('116', 'ISLAS SALOMÓN', 'SB', 'SLB', '677');
INSERT INTO `pais` VALUES ('117', 'ISLAS TURCAS Y CAICOS', 'TC', 'TCA', '1649');
INSERT INTO `pais` VALUES ('118', 'ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS', 'UM', 'UMI', '0');
INSERT INTO `pais` VALUES ('119', 'ISLAS VÍRGENES BRITÁNICAS', 'VG', 'VG', '1284');
INSERT INTO `pais` VALUES ('120', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'VI', 'VIR', '1340');
INSERT INTO `pais` VALUES ('121', 'ISRAEL', 'IL', 'ISR', '972');
INSERT INTO `pais` VALUES ('122', 'ITALIA', 'IT', 'ITA', '39');
INSERT INTO `pais` VALUES ('123', 'JAMAICA', 'JM', 'JAM', '1876');
INSERT INTO `pais` VALUES ('124', 'JAPÓN', 'JP', 'JPN', '81');
INSERT INTO `pais` VALUES ('125', 'JERSEY', 'JE', 'JEY', '0');
INSERT INTO `pais` VALUES ('126', 'JORDANIA', 'JO', 'JOR', '962');
INSERT INTO `pais` VALUES ('127', 'KAZAJISTÁN', 'KZ', 'KAZ', '7');
INSERT INTO `pais` VALUES ('128', 'KENIA', 'KE', 'KEN', '254');
INSERT INTO `pais` VALUES ('129', 'KIRGIZSTÁN', 'KG', 'KGZ', '996');
INSERT INTO `pais` VALUES ('130', 'KIRIBATI', 'KI', 'KIR', '686');
INSERT INTO `pais` VALUES ('131', 'KUWAIT', 'KW', 'KWT', '965');
INSERT INTO `pais` VALUES ('132', 'LÍBANO', 'LB', 'LBN', '961');
INSERT INTO `pais` VALUES ('133', 'LAOS', 'LA', 'LAO', '856');
INSERT INTO `pais` VALUES ('134', 'LESOTO', 'LS', 'LSO', '266');
INSERT INTO `pais` VALUES ('135', 'LETONIA', 'LV', 'LVA', '371');
INSERT INTO `pais` VALUES ('136', 'LIBERIA', 'LR', 'LBR', '231');
INSERT INTO `pais` VALUES ('137', 'LIBIA', 'LY', 'LBY', '218');
INSERT INTO `pais` VALUES ('138', 'LIECHTENSTEIN', 'LI', 'LIE', '423');
INSERT INTO `pais` VALUES ('139', 'LITUANIA', 'LT', 'LTU', '370');
INSERT INTO `pais` VALUES ('140', 'LUXEMBURGO', 'LU', 'LUX', '352');
INSERT INTO `pais` VALUES ('141', 'MÉXICO', 'MX', 'MEX', '52');
INSERT INTO `pais` VALUES ('142', 'MÓNACO', 'MC', 'MCO', '377');
INSERT INTO `pais` VALUES ('143', 'MACAO', 'MO', 'MAC', '853');
INSERT INTO `pais` VALUES ('144', 'MACEDÔNIA', 'MK', 'MKD', '389');
INSERT INTO `pais` VALUES ('145', 'MADAGASCAR', 'MG', 'MDG', '261');
INSERT INTO `pais` VALUES ('146', 'MALASIA', 'MY', 'MYS', '60');
INSERT INTO `pais` VALUES ('147', 'MALAWI', 'MW', 'MWI', '265');
INSERT INTO `pais` VALUES ('148', 'MALI', 'ML', 'MLI', '223');
INSERT INTO `pais` VALUES ('149', 'MALTA', 'MT', 'MLT', '356');
INSERT INTO `pais` VALUES ('150', 'MARRUECOS', 'MA', 'MAR', '212');
INSERT INTO `pais` VALUES ('151', 'MARTINICA', 'MQ', 'MTQ', '0');
INSERT INTO `pais` VALUES ('152', 'MAURICIO', 'MU', 'MUS', '230');
INSERT INTO `pais` VALUES ('153', 'MAURITANIA', 'MR', 'MRT', '222');
INSERT INTO `pais` VALUES ('154', 'MAYOTTE', 'YT', 'MYT', '262');
INSERT INTO `pais` VALUES ('155', 'MICRONESIA', 'FM', 'FSM', '691');
INSERT INTO `pais` VALUES ('156', 'MOLDAVIA', 'MD', 'MDA', '373');
INSERT INTO `pais` VALUES ('157', 'MONGOLIA', 'MN', 'MNG', '976');
INSERT INTO `pais` VALUES ('158', 'MONTENEGRO', 'ME', 'MNE', '382');
INSERT INTO `pais` VALUES ('159', 'MONTSERRAT', 'MS', 'MSR', '1664');
INSERT INTO `pais` VALUES ('160', 'MOZAMBIQUE', 'MZ', 'MOZ', '258');
INSERT INTO `pais` VALUES ('161', 'NAMIBIA', 'NA', 'NAM', '264');
INSERT INTO `pais` VALUES ('162', 'NAURU', 'NR', 'NRU', '674');
INSERT INTO `pais` VALUES ('163', 'NEPAL', 'NP', 'NPL', '977');
INSERT INTO `pais` VALUES ('164', 'NICARAGUA', 'NI', 'NIC', '505');
INSERT INTO `pais` VALUES ('165', 'NIGER', 'NE', 'NER', '227');
INSERT INTO `pais` VALUES ('166', 'NIGERIA', 'NG', 'NGA', '234');
INSERT INTO `pais` VALUES ('167', 'NIUE', 'NU', 'NIU', '683');
INSERT INTO `pais` VALUES ('168', 'NORUEGA', 'NO', 'NOR', '47');
INSERT INTO `pais` VALUES ('169', 'NUEVA CALEDONIA', 'NC', 'NCL', '687');
INSERT INTO `pais` VALUES ('170', 'NUEVA ZELANDA', 'NZ', 'NZL', '64');
INSERT INTO `pais` VALUES ('171', 'OMÁN', 'OM', 'OMN', '968');
INSERT INTO `pais` VALUES ('172', 'PAÍSES BAJOS', 'NL', 'NLD', '31');
INSERT INTO `pais` VALUES ('173', 'PAKISTÁN', 'PK', 'PAK', '92');
INSERT INTO `pais` VALUES ('174', 'PALAU', 'PW', 'PLW', '680');
INSERT INTO `pais` VALUES ('175', 'PALESTINA', 'PS', 'PSE', '0');
INSERT INTO `pais` VALUES ('176', 'PANAMÁ', 'PA', 'PAN', '507');
INSERT INTO `pais` VALUES ('177', 'PAPÚA NUEVA GUINEA', 'PG', 'PNG', '675');
INSERT INTO `pais` VALUES ('178', 'PARAGUAY', 'PY', 'PRY', '595');
INSERT INTO `pais` VALUES ('179', 'PERÚ', 'PE', 'PER', '51');
INSERT INTO `pais` VALUES ('180', 'POLINESIA FRANCESA', 'PF', 'PYF', '689');
INSERT INTO `pais` VALUES ('181', 'POLONIA', 'PL', 'POL', '48');
INSERT INTO `pais` VALUES ('182', 'PORTUGAL', 'PT', 'PRT', '351');
INSERT INTO `pais` VALUES ('183', 'PUERTO RICO', 'PR', 'PRI', '1');
INSERT INTO `pais` VALUES ('184', 'QATAR', 'QA', 'QAT', '974');
INSERT INTO `pais` VALUES ('185', 'REINO UNIDO', 'GB', 'GBR', '44');
INSERT INTO `pais` VALUES ('186', 'REPÚBLICA CENTROAFRICANA', 'CF', 'CAF', '236');
INSERT INTO `pais` VALUES ('187', 'REPÚBLICA CHECA', 'CZ', 'CZE', '420');
INSERT INTO `pais` VALUES ('188', 'REPÚBLICA DOMINICANA', 'DO', 'DOM', '1809');
INSERT INTO `pais` VALUES ('189', 'REUNIÓN', 'RE', 'REU', '0');
INSERT INTO `pais` VALUES ('190', 'RUANDA', 'RW', 'RWA', '250');
INSERT INTO `pais` VALUES ('191', 'RUMANÍA', 'RO', 'ROU', '40');
INSERT INTO `pais` VALUES ('192', 'RUSIA', 'RU', 'RUS', '7');
INSERT INTO `pais` VALUES ('193', 'SAHARA OCCIDENTAL', 'EH', 'ESH', '0');
INSERT INTO `pais` VALUES ('194', 'SAMOA', 'WS', 'WSM', '685');
INSERT INTO `pais` VALUES ('195', 'SAMOA AMERICANA', 'AS', 'ASM', '1684');
INSERT INTO `pais` VALUES ('196', 'SAN BARTOLOMÉ', 'BL', 'BLM', '590');
INSERT INTO `pais` VALUES ('197', 'SAN CRISTÓBAL Y NIEVES', 'KN', 'KNA', '1869');
INSERT INTO `pais` VALUES ('198', 'SAN MARINO', 'SM', 'SMR', '378');
INSERT INTO `pais` VALUES ('199', 'SAN MARTÍN (FRANCIA)', 'MF', 'MAF', '1599');
INSERT INTO `pais` VALUES ('200', 'SAN PEDRO Y MIQUELÓN', 'PM', 'SPM', '508');
INSERT INTO `pais` VALUES ('201', 'SAN VICENTE Y LAS GRANADINAS', 'VC', 'VCT', '1784');
INSERT INTO `pais` VALUES ('202', 'SANTA ELENA', 'SH', 'SHN', '290');
INSERT INTO `pais` VALUES ('203', 'SANTA LUCÍA', 'LC', 'LCA', '1758');
INSERT INTO `pais` VALUES ('204', 'SANTO TOMÉ Y PRÍNCIPE', 'ST', 'STP', '239');
INSERT INTO `pais` VALUES ('205', 'SENEGAL', 'SN', 'SEN', '221');
INSERT INTO `pais` VALUES ('206', 'SERBIA', 'RS', 'SRB', '381');
INSERT INTO `pais` VALUES ('207', 'SEYCHELLES', 'SC', 'SYC', '248');
INSERT INTO `pais` VALUES ('208', 'SIERRA LEONA', 'SL', 'SLE', '232');
INSERT INTO `pais` VALUES ('209', 'SINGAPUR', 'SG', 'SGP', '65');
INSERT INTO `pais` VALUES ('210', 'SIRIA', 'SY', 'SYR', '963');
INSERT INTO `pais` VALUES ('211', 'SOMALIA', 'SO', 'SOM', '252');
INSERT INTO `pais` VALUES ('212', 'SRI LANKA', 'LK', 'LKA', '94');
INSERT INTO `pais` VALUES ('213', 'SUDÁFRICA', 'ZA', 'ZAF', '27');
INSERT INTO `pais` VALUES ('214', 'SUDÁN', 'SD', 'SDN', '249');
INSERT INTO `pais` VALUES ('215', 'SUECIA', 'SE', 'SWE', '46');
INSERT INTO `pais` VALUES ('216', 'SUIZA', 'CH', 'CHE', '41');
INSERT INTO `pais` VALUES ('217', 'SURINÁM', 'SR', 'SUR', '597');
INSERT INTO `pais` VALUES ('218', 'SVALBARD Y JAN MAYEN', 'SJ', 'SJM', '0');
INSERT INTO `pais` VALUES ('219', 'SWAZILANDIA', 'SZ', 'SWZ', '268');
INSERT INTO `pais` VALUES ('220', 'TADJIKISTÁN', 'TJ', 'TJK', '992');
INSERT INTO `pais` VALUES ('221', 'TAILANDIA', 'TH', 'THA', '66');
INSERT INTO `pais` VALUES ('222', 'TAIWÁN', 'TW', 'TWN', '886');
INSERT INTO `pais` VALUES ('223', 'TANZANIA', 'TZ', 'TZA', '255');
INSERT INTO `pais` VALUES ('224', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'IO', 'IOT', '0');
INSERT INTO `pais` VALUES ('225', 'TERRITORIOS AUSTRALES Y ANTÁRTICAS FRANCESES', 'TF', 'ATF', '0');
INSERT INTO `pais` VALUES ('226', 'TIMOR ORIENTAL', 'TL', 'TLS', '670');
INSERT INTO `pais` VALUES ('227', 'TOGO', 'TG', 'TGO', '228');
INSERT INTO `pais` VALUES ('228', 'TOKELAU', 'TK', 'TKL', '690');
INSERT INTO `pais` VALUES ('229', 'TONGA', 'TO', 'TON', '676');
INSERT INTO `pais` VALUES ('230', 'TRINIDAD Y TOBAGO', 'TT', 'TTO', '1868');
INSERT INTO `pais` VALUES ('231', 'TUNEZ', 'TN', 'TUN', '216');
INSERT INTO `pais` VALUES ('232', 'TURKMENISTÁN', 'TM', 'TKM', '993');
INSERT INTO `pais` VALUES ('233', 'TURQUÍA', 'TR', 'TUR', '90');
INSERT INTO `pais` VALUES ('234', 'TUVALU', 'TV', 'TUV', '688');
INSERT INTO `pais` VALUES ('235', 'UCRANIA', 'UA', 'UKR', '380');
INSERT INTO `pais` VALUES ('236', 'UGANDA', 'UG', 'UGA', '256');
INSERT INTO `pais` VALUES ('237', 'URUGUAY', 'UY', 'URY', '598');
INSERT INTO `pais` VALUES ('238', 'UZBEKISTÁN', 'UZ', 'UZB', '998');
INSERT INTO `pais` VALUES ('239', 'VANUATU', 'VU', 'VUT', '678');
INSERT INTO `pais` VALUES ('240', 'VENEZUELA', 'VE', 'VEN', '58');
INSERT INTO `pais` VALUES ('241', 'VIETNAM', 'VN', 'VNM', '84');
INSERT INTO `pais` VALUES ('242', 'WALLIS Y FUTUNA', 'WF', 'WLF', '681');
INSERT INTO `pais` VALUES ('243', 'YEMEN', 'YE', 'YEM', '967');
INSERT INTO `pais` VALUES ('244', 'YIBUTI', 'DJ', 'DJI', '253');
INSERT INTO `pais` VALUES ('245', 'ZAMBIA', 'ZM', 'ZMB', '260');
INSERT INTO `pais` VALUES ('246', 'ZIMBABUE', 'ZW', 'ZWE', '263');
