#
# TABLE STRUCTURE FOR: moneda
#

DROP TABLE IF EXISTS `moneda`;

CREATE TABLE `moneda` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pais` varchar(150) DEFAULT NULL,
  `moneda` varchar(100) DEFAULT NULL,
  `codigo` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=269 DEFAULT CHARSET=latin1;

INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('1', 'AFGANISTÁN', 'Afghani', 'AFN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('2', 'ALBANIA', 'Lek', 'ALL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('3', 'ALEMANIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('4', 'ALGERIA', 'Dinar argelino', 'DZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('5', 'ANDORRA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('6', 'ANGOLA', 'Kwanza', 'AOA');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('7', 'ANGUILA', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('8', 'ANTIGUA Y BARBUDA', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('9', 'ANTÁRTIDA', 'Sin moneda universal', '');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('10', 'ARABIA SAUDITA', 'Riyal saudí', 'SAR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('11', 'ARGENTINA', 'Peso Argentino', 'ARS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('12', 'ARMENIA', 'Dram armenio', 'AMD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('13', 'ARUBA', 'Florín arubeño', 'AWG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('14', 'AUSTRALIA', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('15', 'AUSTRIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('16', 'AZERBAIYÁN', 'Manat azerbaiyano', 'AZN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('17', 'BAHAMAS (LAS)', 'Dólar de las Bahamas', 'BSD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('18', 'BAHRAIN', 'Dinar de Bahrein', 'BHD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('19', 'BANGLADESH', 'Taka', 'BDT');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('20', 'BARBADOS', 'Dólar de Barbados', 'BBD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('21', 'BELICE', 'Dólar de Belice', 'BZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('22', 'BENIN', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('23', 'BERMUDA', 'Dólar de Bermudas', 'BMD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('24', 'BIELORRUSIA', 'Rublo bielorruso', 'BYR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('25', 'BOLIVIA (ESTADO PLURINACIONAL DE)', 'Boliviano', 'BOB');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('26', 'BOLIVIA (ESTADO PLURINACIONAL DE)', 'Mvdol', 'BOV');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('27', 'BONAIRE SAN EUSTAQUIO Y SABA', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('28', 'BOSNIA Y HERZEGOVINA', 'Marco bosnioherzegovino', 'BAM');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('29', 'BOTSWANA', 'Pula', 'BWP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('30', 'BRASIL', 'Real Brasileño', 'BRL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('31', 'BRUNEI DARUSSALAM', 'Dólar de Brunei', 'BND');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('32', 'BULGARIA', 'Lev búlgaro', 'BGN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('33', 'BURKINA FASO', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('34', 'BURUNDI', 'Franco Burundi', 'BIF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('35', 'BUTÁN', 'Ngultrum', 'BTN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('36', 'BUTÁN', 'Rupia india', 'INR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('37', 'BÉLGICA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('38', 'CABO VERDE', 'Cabo Verde Escudo', 'CVE');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('39', 'CAMBOYA', 'Riel', 'KHR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('40', 'CAMERÚN', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('41', 'CANADÁ', 'Dólar canadiense', 'CAD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('42', 'CHAD', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('43', 'CHILE', 'Unidad de Fomento', 'CLF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('44', 'CHILE', 'Peso chileno', 'CLP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('45', 'CHINA', 'Yuan', 'CNY');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('46', 'CHIPRE', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('47', 'COLOMBIA', 'Peso ColombianO', 'COP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('48', 'COLOMBIA', 'Unidad de Valor Real', 'COU');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('49', 'COMOROS', 'Franco Comoro', 'KMF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('50', 'CONGO', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('51', 'CONGO (LA REPÚBLICA DEMOCRÁTICA DEL)', 'Franco congoleño', 'CDF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('52', 'COREA (LA REPÚBLICA DE)', 'Won', 'KRW');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('53', 'COREA (LA REPÚBLICA DEMOCRÁTICA POPULAR)', 'Won norcoreano', 'KPW');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('54', 'COSTA DE MARFIL', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('55', 'COSTA RICA', 'Colón costarricense', 'CRC');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('56', 'CROAcIA', 'Kuna', 'HRK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('57', 'CUBA', 'Peso Convertible', 'CUC');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('58', 'CUBA', 'Peso Cubano', 'CUP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('59', 'CURAZAO', 'Florín antillano neerlandés', 'ANG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('60', 'DINAMARCA', 'Corona danesa', 'DKK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('61', 'DJIBOUTI', 'Franco de Djibouti', 'DJF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('62', 'DOMINICA', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('63', 'ECUADOR', 'DÓlar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('64', 'EGIPTO', 'Libra egipcia', 'EGP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('65', 'EL SALVADOR', 'Colón', 'SVC');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('66', 'EL SALVADOR', 'Dólar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('67', 'EMIRATOS ÁRABES UNIDOS', 'Dírham de los Emiratos Árabes Unidos', 'AED');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('68', 'ERITREA', 'Nakfa', 'ERN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('69', 'ESLOVAQUIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('70', 'ESLOVENIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('71', 'ESPAÑA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('72', 'ESTADOS UNIDOS DE AMÉRICA', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('73', 'ESTADOS UNIDOS DE AMÉRICA', 'Dólar Americano (Next day)', 'USN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('74', 'ESTADOS UNIDOS E ISLAS MENORES', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('75', 'ESTONIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('76', 'ETIOPÍA', 'Birr etíope', 'ETB');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('77', 'FIJI', 'Dólar de Fiji', 'FJD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('78', 'FILIPINAS (LAS)', 'Peso filipino', 'PHP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('79', 'FINLANDIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('80', 'FONDO MONETARIO INTERNACIONAL (IMF)', 'SDR (Derechos Especiales de Giro)', 'XDR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('81', 'FRANCIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('82', 'GABÓN', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('83', 'GAMBIA', 'Dalasi', 'GMD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('84', 'GEORGIA', 'Lari', 'GEL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('85', 'GHANA', 'Cedi de Ghana', 'GHS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('86', 'GIBRALTAR', 'Libra de Gibraltar', 'GIP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('87', 'GRANADA', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('88', 'GRECIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('89', 'GROENLANDIA', 'Corona danesa', 'DKK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('90', 'GUADALUPE', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('91', 'GUAM', 'Dólar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('92', 'GUATEMALA', 'Quetzal', 'GTQ');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('93', 'GUAYANA FRANCESA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('94', 'GUERNESEY', 'Libra esterlina', 'GBP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('95', 'GUINEA', 'Franco guineano', 'GNF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('96', 'GUINEA ECUATORIAL', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('97', 'GUINEA-BISSAU', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('98', 'GUYANA', 'Dólar guyanés', 'GYD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('99', 'HAITÍ', 'Gourde', 'HTG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('100', 'HAITÓ', 'Dólar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('101', 'HONDURAS', 'Lempira', 'HNL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('102', 'HONG KONG', 'Dolar de Hong Kong', 'HKD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('103', 'HUNGRÍA', 'Florín', 'HUF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('104', 'INDIA', 'Rupia india', 'INR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('105', 'INDONESIA', 'Rupia', 'IDR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('106', 'IRAQ', 'Dinar iraquí', 'IQD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('107', 'IRLANDA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('108', 'IRÁN (REPÚBLICA ISLÁMICA DE)', 'Rial iraní', 'IRR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('109', 'ISLA BOUVET', 'Corona noruega', 'NOK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('110', 'ISLA DE MAN', 'Libra esterlina', 'GBP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('111', 'ISLA DE NAVIDAD', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('112', 'ISLA HEARD E ISLAS McDONALD', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('113', 'ISLA NORFOLK', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('114', 'ISLANDIA', 'Corona islandesa', 'ISK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('115', 'ISLAS ALAND', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('116', 'ISLAS CAIMÁN', 'Dólar de las Islas Caimán', 'KYD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('117', 'ISLAS COCO', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('118', 'ISLAS COOK', 'Dólar neozelandés', 'NZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('119', 'ISLAS FEROE', 'Corona danesa', 'DKK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('120', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'Sin moneda universal', '');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('121', 'ISLAS MALVINAS', 'Libra malvinense', 'FKP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('122', 'ISLAS MARIANAS DEL NORTE', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('123', 'ISLAS MARSHALL', 'Dólar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('124', 'ISLAS SALOMÓN', 'Dólar de las Islas Salomón', 'SBD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('125', 'ISLAS VIRGENES (EE.UU.)', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('126', 'ISLAS VÍRGENES (BRITÁNICA)', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('127', 'ISRAEL', 'Nuevo Shekel Israelí', 'ILS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('128', 'ITALIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('129', 'JAMAICA', 'Dólar jamaiquino', 'JMD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('130', 'JAPÓN', 'Yen', 'JPY');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('131', 'JERSEY', 'Libra esterlina', 'GBP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('132', 'JORDANIA', 'Dinar jordano', 'JOD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('133', 'KAZAJSTÁN', 'Tenge', 'KZT');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('134', 'KENIA', 'Chelín keniano', 'KES');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('135', 'KIRGUISTÁN', 'Som', 'KGS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('136', 'KIRIBATI', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('137', 'KUWAIT', 'Dinar kuwaití', 'KWD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('138', 'LAO REPÚBLICA DEMOCRÁTICA POPULAR', 'Kip', 'LAK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('139', 'LESOTHO', 'Loti', 'LSL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('140', 'LESOTHO', 'Rand', 'ZAR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('141', 'LETONIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('142', 'LIBERIA', 'Dólar liberiano', 'LRD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('143', 'LIBIA', 'Dinar libio', 'LYD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('144', 'LIECHTENSTEIN', 'Franco suizo', 'CHF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('145', 'LITUANIA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('146', 'LUXEMBOURG', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('147', 'LÍBANO', 'Libra libanesa', 'LBP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('148', 'MACAO', 'Pataca', 'MOP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('149', 'MACEDONIA (Ex República Yugoslava)', 'Denar', 'MKD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('150', 'MADAGASCAR', 'Ariary malgache', 'MGA');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('151', 'MALASIA', 'Ringgit malayo', 'MYR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('152', 'MALAWI', 'Kwacha', 'MWK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('153', 'MALDIVAS', 'Rufiyaa', 'MVR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('154', 'MALTA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('155', 'MALÍ', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('156', 'MARRUECOS', 'Dirham marroquí', 'MAD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('157', 'MARTINICA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('158', 'MAURICIO', 'Rupia de Mauricio', 'MUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('159', 'MAURITANIA', 'Ouguiya', 'MRO');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('160', 'MAYOTTE', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('161', 'MICRONESIA (ESTADOS FEDERADOS DE)', 'Dólar americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('162', 'MOLDAVIA', 'Leu moldavo', 'MDL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('163', 'MONGOLIA', 'Tugrik', 'MNT');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('164', 'MONTENEGRO', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('165', 'MONTSERRAT', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('166', 'MOZAMBIQUE', 'Metical mozambiqueño', 'MZN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('167', 'MYANMAR', 'Kyat', 'MMK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('168', 'MÉXICO', 'Peso MexicanO', 'MXN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('169', 'MÉXICO', 'Unidad de Inversion Mexicana (UDI)', 'MXV');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('170', 'MÓNACO', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('171', 'NAMIBIA', 'Dólar de Namibia', 'NAD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('172', 'NAMIBIA', 'Rand', 'ZAR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('173', 'NAURU', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('174', 'NEPAL', 'Rupia nepalí', 'NPR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('175', 'NICARAGUA', 'Cordoba Oro', 'NIO');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('176', 'NIGER', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('177', 'NIGERIA', 'Naira', 'NGN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('178', 'NIUE', 'Dólar neozelandés', 'NZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('179', 'NORUEGA', 'Corona noruega', 'NOK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('180', 'NUEVA CALEDONIA', 'Franco CFP', 'XPF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('181', 'NUEVA ZELANDA', 'Dólar neozelandés', 'NZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('182', 'OMÁN', 'Rial omaní', 'OMR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('183', 'PAKISTÁN', 'Rupia pakistaní', 'PKR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('184', 'PALAU', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('185', 'PALESTINA, ESTADO DE', 'Sin moneda universal', '');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('186', 'PANAMÁ', 'Balboa', 'PAB');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('187', 'PANAMÁ', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('188', 'PAPUA NUEVA GUINEA', 'Kina', 'PGK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('189', 'PARAGUAY', 'Guaraní', 'PYG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('190', 'PAÍSES BAJOS', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('191', 'PAÍSES MIEMBROS DEL GRUPO BANCO AFRICANO DEL DESARROLLO', 'Unidad de cuenta del BAD', 'XUA');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('192', 'PERú', 'Nuevo Sol', 'PEN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('193', 'PITCAIRN', 'Dólar neozelandés', 'NZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('194', 'POLINESIA FRANCESA', 'CFP Franc', 'XPF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('195', 'POLONIA', 'Zloty', 'PLN');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('196', 'PORTUGAL', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('197', 'PUERTO RICO', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('198', 'QATAR', 'Riyal catarí', 'QAR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('199', 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE', 'Libra esterlina', 'GBP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('200', 'REPÚBLICA CENTROAFRICANA', 'Franco CFA BEAC', 'XAF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('201', 'REPÚBLICA CHECA', 'Corona checa', 'CZK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('202', 'REPÚBLICA DOMINICANA', 'Peso Dominicano', 'DOP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('203', 'REPÚBLICA ÁRABE SIRIA', 'Libra Siria', 'SYP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('204', 'RUANDA', 'Franco ruandés', 'RWF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('205', 'RUMANIA', 'Leu rumano', 'RON');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('206', 'RUSIA', 'Rublo ruso', 'RUB');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('207', 'RÉUNION', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('208', 'SAHARA OCCIDENTAL', 'Dirham marroquí', 'MAD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('209', 'SAMOA', 'Tala', 'WST');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('210', 'SAMOA AMERICANA', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('211', 'SAN BARTOLOMÉ', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('212', 'SAN CRISTÓBAL Y NIEVES', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('213', 'SAN MARINO', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('214', 'SAN MARTIN (PARTE FRANCESA)', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('215', 'SAN PEDRO Y MIQUELÓN', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('216', 'SAN VICENTE Y LAS GRANADINAS', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('217', 'SANTA ELENA, ASCENSIÓN Y TRISTÁN DE ACUÑA', 'Libra de Santa Helena', 'SHP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('218', 'SANTA LUCÍA', 'Dólar del Caribe Oriental', 'XCD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('219', 'SANTA SEDE', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('220', 'SANTO TOMÉ Y PRÍNCIPE', 'Dobra', 'STD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('221', 'SENEGAL', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('222', 'SERBIA', 'Dinar serbio', 'RSD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('223', 'SEYCHELLES', 'Rupia seychelense', 'SCR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('224', 'SIERRA LEONA', 'Leone', 'SLL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('225', 'SINGAPUR', 'Dolar de Singapur', 'SGD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('226', 'SINT MAARTEN (PARTE HOLANDESA)', 'Florín antillano neerlandés', 'ANG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('227', 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \"\"SUCRE\"\"', 'Sucre', 'XSU');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('228', 'SOMALIA', 'Chelín somalí', 'SOS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('229', 'SRI LANKA', 'Rupia de Sri Lanka', 'LKR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('230', 'SUDÁFRICA', 'Rand', 'ZAR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('231', 'SUDÁN', 'Libra sudanesa', 'SDG');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('232', 'SUDÁN DEL SUR', 'Libra sursudanesa', 'SSP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('233', 'SUECIA', 'Corona sueca', 'SEK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('234', 'SUIZA', 'Euro WIR', 'CHE');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('235', 'SUIZA', 'Franco suizo', 'CHF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('236', 'SUIZA', 'Franco WIR', 'CHW');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('237', 'SURINAME', 'Dólar surinamés', 'SRD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('238', 'SVALBARD AND JAN MAYEN', 'Corona noruega', 'NOK');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('239', 'SWAZILANDIA', 'Lilangeni', 'SZL');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('240', 'TAILANDIA', 'Baht', 'THB');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('241', 'TAIWÁN (PROVINCIA DE CHINA)', 'Nuevo dólar taiwanés', 'TWD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('242', 'TANZANIA, REPÚBLICA UNIDA DE', 'Chelín tanzano', 'TZS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('243', 'TAYIKISTÁN', 'Somoni', 'TJS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('244', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('245', 'TERRITORIOS AUSTRALES FRANCESES', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('246', 'TIMOR ORIENTAL', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('247', 'TOGO', 'Franco CFA BCEAO', 'XOF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('248', 'TOKELAU', 'Dólar neozelandés', 'NZD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('249', 'TONGA', 'Pa’anga', 'TOP');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('250', 'TRINIDAD Y TOBAGO', 'Dólar trinitense', 'TTD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('251', 'TURCOS Y CAICOS', 'Dólar Americano', 'USD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('252', 'TURKMENISTÁN', 'Manat turcomano', 'TMT');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('253', 'TURQUÍA', 'Lira turca', 'TRY');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('254', 'TUVALU', 'Dólar australiano', 'AUD');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('255', 'TÚNEZ', 'Dinar tunecino', 'TND');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('256', 'UCRANIA', 'Hryvnia', 'UAH');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('257', 'UGANDA', 'Chelín ugandés', 'UGX');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('258', 'UNIÓN EUROPEA', 'Euro', 'EUR');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('259', 'URUGUAY', 'Uruguay Peso en Unidades Indexadas (URUIURUI)', 'UYI');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('260', 'URUGUAY', 'Peso Uruguayo', 'UYU');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('261', 'UZBEKISTÁN', 'Som uzbeko', 'UZS');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('262', 'VANUATU', 'Vatu', 'VUV');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('263', 'VENEZUELA (REPÚBLICA BOLIVARIANA DE)', 'Bolívar', 'VEF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('264', 'VIETNAM', 'Dong', 'VND');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('265', 'WALLIS Y FUTUNA', 'Franco CFP', 'XPF');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('266', 'YEMEN', 'Rial yemení', 'YER');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('267', 'ZAMBIA', 'Kwacha zambiano', 'ZMW');
INSERT INTO `moneda` (`id`, `pais`, `moneda`, `codigo`) VALUES ('268', 'ZIMBABWE', 'Dólar zimbabuense', 'ZWL');


